[tool.black]
target-version = ["py39", "py310"]
color = true
skip_magic_trailing_comma = true
exclude = '''
(
/(
    \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | Swin-Transformer
)/
)
'''

[tool.isort]
profile = "black"
known_first_party = ["src"]
skip_gitignore = true
skip_glob = "Swin-Transformer/*"
